# Generated by Django 2.2.6 on 2019-10-14 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('longitude', models.DecimalField(decimal_places=20, max_digits=30)),
                ('latitude', models.DecimalField(decimal_places=20, max_digits=30)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.CharField(max_length=400)),
                ('place_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='turistas_rec.Place')),
            ],
        ),
    ]
