# Generated by Django 2.2.6 on 2019-10-14 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turistas_rec', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='place',
            name='description',
            field=models.ManyToManyField(related_name='description', to='turistas_rec.Category'),
        ),
    ]
