# Generated by Django 2.2.6 on 2020-02-25 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turistas_rec', '0002_auto_20191014_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='howtoreach',
            field=models.CharField(default='nil', max_length=100),
        ),
        migrations.AddField(
            model_name='place',
            name='image',
            field=models.ImageField(default='images/sample.jpg', upload_to=None),
        ),
        migrations.AddField(
            model_name='place',
            name='ratings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='place',
            name='specification',
            field=models.ManyToManyField(related_name='description', to='turistas_rec.Category'),
        ),
        migrations.AddField(
            model_name='place',
            name='view',
            field=models.CharField(default='nil', max_length=100),
        ),
        migrations.AddField(
            model_name='place',
            name='visited',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='place',
            name='description',
        ),
        migrations.AddField(
            model_name='place',
            name='description',
            field=models.CharField(default='nil', max_length=100),
        ),
        migrations.AlterField(
            model_name='place',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=30),
        ),
        migrations.AlterField(
            model_name='place',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=30),
        ),
    ]
