# Generated by Django 2.2.6 on 2020-03-12 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turistas_rec', '0004_auto_20200312_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='howtoreach',
            field=models.CharField(default='nil', max_length=1000),
        ),
    ]
