# Generated by Django 2.2.6 on 2020-03-12 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turistas_rec', '0005_auto_20200312_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='sent',
            field=models.IntegerField(default=0),
        ),
    ]
